# 👉 It is a configuration file for pytest
# 👉 To control how pytest runs your tests without changing code.

[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests

testpaths = tests

# --tb=short , clean + small error output instead of long confusing logs
addopts = -v -s --tb=short --alluredir=allure-results --platform=android

