name: Mobile_Appium_Advanced_CICD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      device:
        description: "android / ios / both"
        required: true
        default: both
        type: choice
        options:
          - android
          - ios
          - both

jobs:
  test:
    name: test (${{ matrix.device }})
    runs-on: ${{ matrix.device == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    timeout-minutes: 40

    strategy:
      fail-fast: false
      matrix:
        device: [android]

    if: github.event_name == 'push' || github.event.inputs.device == 'both'

    env:
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # ✅ Appium setup for Android
      - name: Install Appium and Android Drivers
        run: |
          npm install -g appium@2
          appium driver install uiautomator2@2.30.0

      # ✅ Appium setup for IOS
      - name: Install iOS Driver
        if: matrix.device == 'ios'
        run: |
          appium driver install xcuitest

      # ✅ ANDROID FLOW
      - name: Setup Java 17 (for Android setup)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        if: matrix.device == 'android'
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: false

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android Packages
        run: |
          sdkmanager "platform-tools"
          sdkmanager "emulator"
          sdkmanager "platforms;android-29"
          sdkmanager "system-images;android-29;google_apis;x86_64"

      - name: Add Emulator to PATH
        run: |
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Setup Latest Cmdline Tools
        run: |
          rm -rf $ANDROID_HOME/cmdline-tools/latest   # 🔥 clean old
          
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
      
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip tools.zip
          
          mv cmdline-tools latest
      
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Prepare Android Folder
        run: |
          mkdir -p ~/.android
          chmod -R 777 ~/.android

      - name: Kill adb (clean state)
        run: |
          adb kill-server || true
          adb start-server || true

      - name: Create AVD
        run: |
          mkdir -p ~/.android/avd
          mkdir -p ~/.android

          echo "no" | avdmanager create avd \
            -n test \
            -k "system-images;android-29;google_apis;x86_64" \
            --device "pixel" \
            --sdcard 512M \
            --force || true

          echo "===== DEBUG AVD LIST ====="
          avdmanager list avd || true

          echo "===== DEBUG FOLDER ====="
          ls -R ~/.android || true

      - name: Set AVD Path
        run: |
          echo "ANDROID_AVD_HOME=$HOME/.config/.android/avd" >> $GITHUB_ENV

      - name: Start Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test \
            -no-window -no-audio -no-boot-anim \
            -gpu off \               
            -accel off \
            -no-snapshot \             
            -no-snapshot-save \         
            -no-snapshot-load >/dev/null 2>&1 &
        
          adb wait-for-device
      
          adb devices
      
          echo "Waiting for full boot..."
          boot_completed="0"
          for i in {1..60}; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            if [ "$boot_completed" = "1" ]; then
              echo "Emulator booted!"
              break
            fi
            sleep 5
          done
      
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot"
            adb logcat -d | tail -n 50
            exit 1
          fi
      
          adb shell input keyevent 82
      
          # Disable animations
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      # ✅ Download APK
      - name: Download App (Android)
        if: matrix.device == 'android'
        run: |
            wget https://github.com/ranjangowda123/mobile-automation-framework-appium-python/releases/download/v1/android_app.apk

      # ✅ Install App (Android)
      - name: Install App (Android)
        if: matrix.device == 'android'
        run: adb install android_app.apk

      # ✅ IOS REAL FLOW
      - name: Setup iOS Simulator
        if: matrix.device == 'ios'
        run: |
          xcodebuild -version
          echo "Available devices:"
          xcrun simctl list devices available

          # Get first available iPhone simulator
          DEVICE=$(xcrun simctl list devices available | grep "iPhone" | head -n 1 | awk -F '[()]' '{print $2}')
    
          echo "Using device: $DEVICE"
    
          xcrun simctl boot "$DEVICE" || true
      
          # Save for next steps
          echo "DEVICE_ID=$DEVICE" >> $GITHUB_ENV

      - name: Wait for iOS Simulator Ready
        if: matrix.device == 'ios'
        run: |
          xcrun simctl bootstatus "$DEVICE_ID" -b

      # ✅ Install App (iOS)
      - name: Install App (iOS)
        if: matrix.device == 'ios'
        run:  |
              xcrun simctl install "$DEVICE_ID" apps/ios_app.app

      # ✅ Start Appium
      - name: Start Appium Server
        run: |
          appium --log-level error &
          sleep 15

      # ✅ ADD THIS
      - name: Verify Appium is running
        run: |
          curl http://127.0.0.1:4723/status

      # ✅ Run tests
      - name: Run Tests
        run: |
          pytest -n 2 \
          -m regression \
          --reruns 2 \
          --reruns-delay 5 \
          --alluredir=allure-results \
          --maxfail=1 --disable-warnings \
          --device=${{ matrix.device }}

      # ✅ Reports & Artifacts - Final Version
      # Upload logs, screenshots, and Allure results as artifacts
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.device }}
          path: |
            allure-results
            reports/screenshots/
            reports/log_path/

      # Install Allure CLI
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.36.0/allure-2.36.0.tgz
          tar -zxvf allure-2.36.0.tgz
          sudo mv allure-2.36.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Load Allure History Trend
      - name: Load Allure History
        if: always()
        run: |
          mkdir -p allure-results/history
          if [ -d allure-history ]; then
            cp -r allure-history/* allure-results/history || true
          fi

      # Add executor.json
      - name: Add Allure Executor
        run: |
          mkdir -p allure-results
          echo '{
            "name": "GitHub Actions",
            "type": "github",
            "buildOrder": "${{ github.run_number }}"
          }' > allure-results/executor.json

      # Generate HTML Allure report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # Save Allure History Trend
      - name: Save Allure History
        if: always()
        run: |
          mkdir -p allure-history
          if [ -d allure-report/history ]; then
            cp -r allure-report/history/* allure-history || true
          fi

      # Publish Allure report to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: ${{ matrix.device }}